### ISSUE TITLE
[bug]exclude option do not test sub dir file

### ISSUE THREAD

**Issue by Inori-Lover** [silverwind/precompress#11]
expect:
when i exclude **.png, cli should not include file like "sub-dir/foo.png"

actual:
precompress inclue every file in sub-dir, even .gz/.br file

command:
```bash
precompress --exclude=**.png,**.xlsx ./dist
```

ps: i think the source is [here](https://github.com/silverwind/precompress/blob/master/precompress.js#L229).

**Comment by Inori-Lover** [comment]
one more thing, i am not sure if [here](https://github.com/silverwind/precompress/blob/master/precompress.js#L25) have not include the "exclude" command will influence the command parse result.

**Comment by silverwind** [comment]
The problem seems to come from how the destination directory is specified. The matchers work with `dist` but not with `./dist`.

**Comment by silverwind** [comment]
It seems to come from [picomatch](https://github.com/micromatch/picomatch):

```js
> (await import("picomatch")).default(["**.js"])("./dist/foo.js")
false
> (await import("picomatch")).default(["**.js"])("dist/foo.js")
true
```

**Comment by silverwind** [comment]
Actual fix in https://github.com/silverwind/rrdir/commit/22dafeaee83358f451cbc9551241689a51c98e07.

**Comment by silverwind** [comment]
Reported upstream as well: https://github.com/micromatch/picomatch/issues/121

**Comment by silverwind** [comment]
> one more thing, i am not sure if [here](https://github.com/silverwind/precompress/blob/master/precompress.js#L25) have not include the "exclude" command will influence the command parse result.

CLI options are fine. `e` is only aliased to `exclude` and both `-e '**.js,**.css'` and `-e '**.js' -e '**.css'` syntaxes will work.
